// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrUq5TOLbhioF7aMCZ4Y6Iq8z9twjUUuc',
    appId: '1:667089127479:web:8c03e7d2c7538a7b7ed7b2',
    messagingSenderId: '667089127479',
    projectId: 'project-callme',
    authDomain: 'project-callme.firebaseapp.com',
    storageBucket: 'project-callme.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLHO5dytKDwjBd5vFtcUt9muei3YIWtd0',
    appId: '1:667089127479:android:f339bf2d543fd7427ed7b2',
    messagingSenderId: '667089127479',
    projectId: 'project-callme',
    storageBucket: 'project-callme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB49w05haWYOvwqxqGNoaG1fVnoCYnUup8',
    appId: '1:667089127479:ios:5547924edaa0b1997ed7b2',
    messagingSenderId: '667089127479',
    projectId: 'project-callme',
    storageBucket: 'project-callme.appspot.com',
    iosClientId: '667089127479-729j01oqhain3l27969l67ev4c3fsa63.apps.googleusercontent.com',
    iosBundleId: 'com.example.callme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB49w05haWYOvwqxqGNoaG1fVnoCYnUup8',
    appId: '1:667089127479:ios:b81e8b496ae064aa7ed7b2',
    messagingSenderId: '667089127479',
    projectId: 'project-callme',
    storageBucket: 'project-callme.appspot.com',
    iosClientId: '667089127479-44e7bft0j9422k61l5vfrn30crl6g3k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.callme.RunnerTests',
  );
}
